name: Check code format

on:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check code format with prettier
        run: |
          npx -y prettier . --check --ignore-path .gitignore

  csharpier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Check code format with csharpier
        run: |
          dotnet tool restore
          dotnet dotnet-csharpier --check .
